# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Csync < Formula
  desc ""
  homepage "https://katallaxie.github.io/csync/"
  version "0.5.16"
  license "APACHE-2.0"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/katallaxie/csync/releases/download/v0.5.16/csync_0.5.16_darwin_arm64.tar.gz"
      sha256 "5fd37a160be4f9af198824f3616f138149b08d4bd9be991a720ca2c12a10006e"

      def install
        bin.install "csync"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/katallaxie/csync/releases/download/v0.5.16/csync_0.5.16_darwin_amd64.tar.gz"
      sha256 "b13fffc1f9810f762c7b49b65fd3582267abdb18cabb4fb3167dc5a58ad23f14"

      def install
        bin.install "csync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/katallaxie/csync/releases/download/v0.5.16/csync_0.5.16_linux_amd64.tar.gz"
      sha256 "a79f361dce815db9685b91eb97302d37a9be7388c61eaaa7af34de260e373f1b"

      def install
        bin.install "csync"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/katallaxie/csync/releases/download/v0.5.16/csync_0.5.16_linux_arm.tar.gz"
      sha256 "158826da32c0fa94d841ee0ddd2036a3e3f8f2d5648890175958d1f5357206cd"

      def install
        bin.install "csync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/katallaxie/csync/releases/download/v0.5.16/csync_0.5.16_linux_arm64.tar.gz"
      sha256 "6e0ae69d831ac378d1dd5e93cf81fa1fbe7143d59ad36b109e0b8236c6db98b1"

      def install
        bin.install "csync"
      end
    end
  end
end
