# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Csync < Formula
  desc ""
  homepage "https://katallaxie.github.io/csync/"
  version "0.1.0-alpha.3"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/katallaxie/csync/releases/download/v0.1.0-alpha.3/csync_0.1.0-alpha.3_darwin_amd64.tar.gz"
      sha256 "5739ad3aa63ddf581e01a4fd6d4b27fe724f3970ae70bdba14223253d66e6b20"

      def install
        bin.install "csync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/katallaxie/csync/releases/download/v0.1.0-alpha.3/csync_0.1.0-alpha.3_darwin_arm64.tar.gz"
      sha256 "3ab53ee4e360dc13f9132b5c78ff8b007161d6512378bcef3cf1bf6cf50c206c"

      def install
        bin.install "csync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/katallaxie/csync/releases/download/v0.1.0-alpha.3/csync_0.1.0-alpha.3_linux_amd64.tar.gz"
      sha256 "e3825b778c2dcd757554aa480345a99b6058c29913075819c3aaed5708a3af08"

      def install
        bin.install "csync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/katallaxie/csync/releases/download/v0.1.0-alpha.3/csync_0.1.0-alpha.3_linux_arm64.tar.gz"
      sha256 "4f08cabc9029ce2387d2635773adf5fb8048dd9babfe3a02b0701305277f123f"

      def install
        bin.install "csync"
      end
    end
  end
end
